### ISSUE TITLE
Test MergeToolTest#testEmptyToolName started failing long time after it was implemented

### ISSUE THREAD

**Issue by msohn** [eclipse-jgit/jgit#115]
### Version

stable-6.10 (f27ea51026)

### Operating System

Linux/Unix

### Bug description

The test which is only run on Linux fails with an assertion error, see e.g. https://ci.eclipse.org/jgit/job/stable/job/jgit.gerrit-pipeline.java11/3016/consoleFull

### Actual behavior

The test fails reproducibly

### Expected behavior

The test should succeed

### Relevant log output

```Shell
03:34:38  [ERROR] Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.562 s <<< FAILURE! -- in org.eclipse.jgit.pgm.MergeToolTest
03:34:38  [ERROR] org.eclipse.jgit.pgm.MergeToolTest.testEmptyToolName -- Time elapsed: 0.709 s <<< FAILURE!
03:34:38  org.junit.ComparisonFailure: Expected no standard error output from tool expected:<[compare[: unrecognized option `-wait' @ error/compare.c/CompareImageCommand/1123., compare: unrecognized option `-wait' @ error/compare.c/CompareImageCommand/1123].]> but was:<[compare[-im6.q16: unrecognized option `-wait' @ error/compare.c/CompareImageCommand/1131., compare-im6.q16: unrecognized option `-wait' @ error/compare.c/CompareImageCommand/1131].]>
03:34:38  	at org.junit.Assert.assertEquals(Assert.java:117)
03:34:38  	at org.eclipse.jgit.pgm.ToolTestCase.runAndCaptureUsingInitRaw(ToolTestCase.java:112)
03:34:38  	at org.eclipse.jgit.pgm.ToolTestCase.runAndCaptureUsingInitRaw(ToolTestCase.java:79)
03:34:38  	at org.eclipse.jgit.pgm.MergeToolTest.testEmptyToolName(MergeToolTest.java:96)
```

**Comment by tomaswolf** [comment]
The test assumes a particular stderr output from an external program. Looks like we now have a different version of that external program, which produces a slightly different stderr output.

This is most likely a result of the [OS change on the Jenkins agents](https://www.eclipse.org/lists/cross-project-issues-dev/msg19990.html). Our tests now run on Ubuntu 24.04.
