### ISSUE TITLE
Apache HTTP client Connection reset

### ISSUE THREAD

**Issue by stefandrissen** [eclipse-jgit/jgit#59]
### Version

6.9.0

### Operating System

Windows

### Bug description

For another issue I am having with an older version of JGit (in a bundled Eclipse 4.23) I am looking at what current vanilla behavior is using latest Eclipse 2024-03.

- Clone remote repo (Azure DevOps) using defaults
- Receiving objects 100% 214501/214501
- Resolving deltas  100% 113302/113302

-> Problem Occurred 
'Cloning from https://dev.azure.com/org/project/_git/repo' has encountered a problem.

Connection reset

Details:

Connection reset
Connection reset

If I then open the issue from the problem view:

![image](https://github.com/eclipse-jgit/jgit/assets/5297464/0f9b8b4a-c777-480d-93cd-ccd231acba02)

I am unsure if the connection reset is a result of the timeout, so I increased the Connection timeout in Git preferences to 300 and then to 600 with the same failure as a result.
 
I then changed the HTTP client to Java built-in HTTP (initially Apache HTTP)

-> repo cloned successfully

My older (bundled) Eclipse 4.23 with JGit 5.13.0 had no issue cloning the repo using Apache HTTP.

### Actual behavior

![image](https://github.com/eclipse-jgit/jgit/assets/5297464/558818cb-722a-46f0-aaea-1f0bf052eb6b)

### Expected behavior

A successful clone.

### Relevant log output

```Shell
!ENTRY org.eclipse.egit.ui 4 0 2024-05-29 09:19:34.145
!MESSAGE Connection reset
!STACK 0
org.eclipse.jgit.api.errors.TransportException: Connection reset
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:249)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:319)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:189)
	at org.eclipse.egit.core.op.CloneOperation.run(CloneOperation.java:194)
	at org.eclipse.egit.ui.internal.clone.AbstractGitCloneWizard.executeCloneOperation(AbstractGitCloneWizard.java:490)
	at org.eclipse.egit.ui.internal.clone.AbstractGitCloneWizard$6.run(AbstractGitCloneWizard.java:464)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.jgit.errors.TransportException: Connection reset
	at org.eclipse.jgit.transport.TransportHttp$SmartHttpFetchConnection.doFetch(TransportHttp.java:1569)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:351)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:343)
	at org.eclipse.jgit.transport.FetchProcess.fetchObjects(FetchProcess.java:290)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:182)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:105)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1482)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:238)
	... 6 more
Caused by: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.read(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(Unknown Source)
	at java.base/java.net.Socket$SocketInputStream.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:261)
	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:222)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:183)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:210)
	at org.apache.http.impl.io.ChunkedInputStream.close(ChunkedInputStream.java:312)
	at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:142)
	at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
	at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172)
	at org.eclipse.jgit.util.io.UnionInputStream.close(UnionInputStream.java:168)
	at org.eclipse.jgit.transport.TransportHttp$SmartHttpFetchConnection.doFetch(TransportHttp.java:1566)
	... 13 more
```

### Other information

Cloning from a private AzDO repo.

**Comment by msohn** [comment]
Connection reset maybe caused by network issues or the the server closing the connection.

**Comment by kwin** [comment]
@msohn As built-in Java HTTP does not suffer from the same issue I assume that retries/timeouts are set differently. Also it seems that it worked with older versions, so unlikely to be just a server/networking issue which cannot be solved inside Jgit.

**Comment by kwin** [comment]
Compare with https://issues.apache.org/jira/browse/MRESOLVER-383 for a similar issue which was resolved by reducing the pooled connection's TTL.

**Comment by tomaswolf** [comment]
@kwin If I understand this right, possible solutions would be to switch to the 5.x Apache HTTP client, or add after

https://github.com/eclipse-jgit/jgit/blob/c318c8a435f584ac00d1cb24292da0f8a956707d/org.eclipse.jgit.http.apache/src/org/eclipse/jgit/transport/http/apache/HttpClientConnection.java#L141-L149
```
} else {
  clientBuilder.setConnectionTimeToLive(300, TimeUnit.SECONDS);
}
```
(of course not with a hard-coded value; should be overrideable by some property, but default to 300).

Is that right?

**Comment by kwin** [comment]
> possible solutions would be to switch to the 5.x Apache HTTP client

This is IMHO not yet fixed there either.

But setting a configurable connection timeout should suffice, yes!

**Comment by kwin** [comment]
Proposed fix in https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1219703.

**Comment by tomaswolf** [comment]
I've pushed https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1219744 as an alternative.

**Comment by kwin** [comment]
Even if there is one dedicated HTTP Client per Git fetch request there still is the chance that connection pooling is relevant for chunked responses (i.e. HTTP connections being reused for subsequent chunks). However except for really large fetches it is unlikely to ever run into a timeout.

**Comment by tomaswolf** [comment]
https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1219744 is merged.
